### ISSUE TITLE
Deploy a simple NGINX application to test the connection

### ISSUE THREAD

**Issue by saudkhan116** [ARENA2036/tx-umbrella#9]
## Description

After setting up a cluster and DNS configurations. deploy a simple Nginx application to test the connection outside the cluster and over the internet.

The below yaml content can be used to deploy a simple app.

Replace <`HOSTNAME`> with the one obtained from DNS settings.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: addon-http-application-routing
      #nginx.ingress.kubernetes.io/cors-allow-origin: <HOSTNAME>
      #nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      #nginx.ingress.kubernetes.io/cors-allow-methods: GET
      #nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
    - secretName: "nginx.test-tls"
      hosts:
        - "<HOSTNAME>"
  rules:
    - <HOSTNAME>
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: nginx-service
              port:
                number: 8080
```
